---
# ------------------------------------------
# Implement your workload removal tasks here
# ------------------------------------------

- name: Deprovision your workload
  ansible.builtin.debug:
    msg: "Removal is not implemented."